### ISSUE TITLE
QVMEditor won't start

### ISSUE THREAD

**Issue by Lognews** [Jones-HM/IGI-QVMEditor#1]
gives a message on startup
------------------------------------------------------------------------------------------------------
Fatal sytem - Error
---------------------------
QVVM Editor Appdata directory is invalid Error: (0x0000000F)
Reason: 'QEditor' Directory is missing
Please re-install new copy from Setup file.
---------------------------
ОК   
---------------------------------------------------------------------------------------------------

when copying the editor files to the directory with the game, nothing changes

**Comment by heaven-hm** [comment]
You need to download QEditor needed for this to work.

[QEditor](https://www.mediafire.com/file/g7y4z1g94l088a5/QEditor.7z/file) and please in your `APPDATA` Roaming folder

Or Just re-install it will automatically place new `QEditor` into your `APPDATA` roaming folder

**Comment by Lognews** [comment]
Thank you! The problem with starting QVMEditor has been resolved.
-----------------------------------------------------------------------------------
I want to try to increase the size of the HUD and text tasks in the game, which is necessary for playing in high resolution 1920 * 1080. Maybe you know if it is possible to do this with the help of QVMEditor, for example, by making edits in the ingamemenu.qvm file or the HUD sizes are protected in the exe file ?

**Comment by heaven-hm** [comment]
> ## Thank you! The problem with starting QVMEditor has been resolved.
> I want to try to increase the size of the HUD and text tasks in the game, which is necessary for playing in high resolution 1920 * 1080. Maybe you know if it is possible to do this with the help of QVMEditor, for example, by making edits in the ingamemenu.qvm file or the HUD sizes are protected in the exe file ?

Yes its possible just go to ingamemenu.qvm and mainmenu.qvm you can use different fonts and sizes, but there are predefined fonts and size available through constants in game make sure you use them only otherwise it will give error.

**Comment by Lognews** [comment]
Thanks. I'll check it out.
