### ISSUE TITLE
Appdata directory is invalid

### ISSUE THREAD

**Issue by CptMacTavish404** [Jones-HM/IGI-QVMEditor#2]
![image](https://github.com/Jones-HM/IGI-QVMEditor/assets/98734231/31c3bea4-75a0-4ec9-80ab-07229b8b2ecc)

**Comment by OsandaLakshitha** [comment]
I got the same error

**Comment by haseeb-heaven** [comment]
You need to download QEditor needed for this to work.

Download [QEditor](https://www.mediafire.com/file/g7y4z1g94l088a5/QEditor.7z/file) and please place inside your APPDATA Roaming folder

Or Just re-install it will automatically place new **QEditor** into your **APPDATA** roaming folder

Run this command in current directory to move **QEditor** to appdata

`move QEditor "%AppData%\QEditor"`

**Comment by heaven-hm** [comment]
Its build in latest commit
[BugFix#2](https://github.com/Jones-HM/IGI-QVMEditor/commit/b2f5f80cca754f80e18a0b1e33ac78e39b8b2f73)

**Comment by heaven-hm** [comment]
Fixed in version 0.4
